// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: alarm.proto
#ifndef GRPC_alarm_2eproto__INCLUDED
#define GRPC_alarm_2eproto__INCLUDED

#include "alarm.pb.h"

#include <functional>
#include <grpc/impl/codegen/port_platform.h>
#include <grpcpp/impl/codegen/async_generic_service.h>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/client_context.h>
#include <grpcpp/impl/codegen/completion_queue.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/codegen/rpc_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/impl/codegen/stub_options.h>
#include <grpcpp/impl/codegen/sync_stream.h>

namespace audioalarm {
namespace v1 {

class AlarmService final {
 public:
  static constexpr char const* service_full_name() {
    return "audioalarm.v1.AlarmService";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    // call alarm interface
    virtual ::grpc::Status SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::audioalarm::v1::AlarmReply* response) = 0;
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>> AsyncSetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>>(AsyncSetAlarmMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>> PrepareAsyncSetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>>(PrepareAsyncSetAlarmMessageRaw(context, request, cq));
    }
    class experimental_async_interface {
     public:
      virtual ~experimental_async_interface() {}
      // call alarm interface
      virtual void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, std::function<void(::grpc::Status)>) = 0;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      virtual void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, ::grpc::ClientUnaryReactor* reactor) = 0;
      #else
      virtual void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) = 0;
      #endif
    };
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    typedef class experimental_async_interface async_interface;
    #endif
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    async_interface* async() { return experimental_async(); }
    #endif
    virtual class experimental_async_interface* experimental_async() { return nullptr; }
  private:
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>* AsyncSetAlarmMessageRaw(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface< ::audioalarm::v1::AlarmReply>* PrepareAsyncSetAlarmMessageRaw(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::audioalarm::v1::AlarmReply* response) override;
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>> AsyncSetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>>(AsyncSetAlarmMessageRaw(context, request, cq));
    }
    std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>> PrepareAsyncSetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>>(PrepareAsyncSetAlarmMessageRaw(context, request, cq));
    }
    class experimental_async final :
      public StubInterface::experimental_async_interface {
     public:
      void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, std::function<void(::grpc::Status)>) override;
      #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, ::grpc::ClientUnaryReactor* reactor) override;
      #else
      void SetAlarmMessage(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response, ::grpc::experimental::ClientUnaryReactor* reactor) override;
      #endif
     private:
      friend class Stub;
      explicit experimental_async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class experimental_async_interface* experimental_async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class experimental_async async_stub_{this};
    ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>* AsyncSetAlarmMessageRaw(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader< ::audioalarm::v1::AlarmReply>* PrepareAsyncSetAlarmMessageRaw(::grpc::ClientContext* context, const ::audioalarm::v1::AlarmRequest& request, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_SetAlarmMessage_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    // call alarm interface
    virtual ::grpc::Status SetAlarmMessage(::grpc::ServerContext* context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_SetAlarmMessage() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetAlarmMessage(::grpc::ServerContext* context, ::audioalarm::v1::AlarmRequest* request, ::grpc::ServerAsyncResponseWriter< ::audioalarm::v1::AlarmReply>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_SetAlarmMessage<Service > AsyncService;
  template <class BaseClass>
  class ExperimentalWithCallbackMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithCallbackMethod_SetAlarmMessage() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::audioalarm::v1::AlarmRequest, ::audioalarm::v1::AlarmReply>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::audioalarm::v1::AlarmRequest* request, ::audioalarm::v1::AlarmReply* response) { return this->SetAlarmMessage(context, request, response); }));}
    void SetMessageAllocatorFor_SetAlarmMessage(
        ::grpc::experimental::MessageAllocator< ::audioalarm::v1::AlarmRequest, ::audioalarm::v1::AlarmReply>* allocator) {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::GetHandler(0);
    #else
      ::grpc::internal::MethodHandler* const handler = ::grpc::Service::experimental().GetHandler(0);
    #endif
      static_cast<::grpc::internal::CallbackUnaryHandler< ::audioalarm::v1::AlarmRequest, ::audioalarm::v1::AlarmReply>*>(handler)
              ->SetMessageAllocator(allocator);
    }
    ~ExperimentalWithCallbackMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetAlarmMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetAlarmMessage(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/)
    #endif
      { return nullptr; }
  };
  #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
  typedef ExperimentalWithCallbackMethod_SetAlarmMessage<Service > CallbackService;
  #endif

  typedef ExperimentalWithCallbackMethod_SetAlarmMessage<Service > ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_SetAlarmMessage() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_SetAlarmMessage() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestSetAlarmMessage(::grpc::ServerContext* context, ::grpc::ByteBuffer* request, ::grpc::ServerAsyncResponseWriter< ::grpc::ByteBuffer>* response, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class ExperimentalWithRawCallbackMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    ExperimentalWithRawCallbackMethod_SetAlarmMessage() {
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
      ::grpc::Service::
    #else
      ::grpc::Service::experimental().
    #endif
        MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackUnaryHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
                   ::grpc::CallbackServerContext*
    #else
                   ::grpc::experimental::CallbackServerContext*
    #endif
                     context, const ::grpc::ByteBuffer* request, ::grpc::ByteBuffer* response) { return this->SetAlarmMessage(context, request, response); }));
    }
    ~ExperimentalWithRawCallbackMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    #ifdef GRPC_CALLBACK_API_NONEXPERIMENTAL
    virtual ::grpc::ServerUnaryReactor* SetAlarmMessage(
      ::grpc::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #else
    virtual ::grpc::experimental::ServerUnaryReactor* SetAlarmMessage(
      ::grpc::experimental::CallbackServerContext* /*context*/, const ::grpc::ByteBuffer* /*request*/, ::grpc::ByteBuffer* /*response*/)
    #endif
      { return nullptr; }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_SetAlarmMessage : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithStreamedUnaryMethod_SetAlarmMessage() {
      ::grpc::Service::MarkMethodStreamed(0,
        new ::grpc::internal::StreamedUnaryHandler<
          ::audioalarm::v1::AlarmRequest, ::audioalarm::v1::AlarmReply>(
            [this](::grpc::ServerContext* context,
                   ::grpc::ServerUnaryStreamer<
                     ::audioalarm::v1::AlarmRequest, ::audioalarm::v1::AlarmReply>* streamer) {
                       return this->StreamedSetAlarmMessage(context,
                         streamer);
                  }));
    }
    ~WithStreamedUnaryMethod_SetAlarmMessage() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status SetAlarmMessage(::grpc::ServerContext* /*context*/, const ::audioalarm::v1::AlarmRequest* /*request*/, ::audioalarm::v1::AlarmReply* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedSetAlarmMessage(::grpc::ServerContext* context, ::grpc::ServerUnaryStreamer< ::audioalarm::v1::AlarmRequest,::audioalarm::v1::AlarmReply>* server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_SetAlarmMessage<Service > StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_SetAlarmMessage<Service > StreamedService;
};

}  // namespace v1
}  // namespace audioalarm


#endif  // GRPC_alarm_2eproto__INCLUDED
